### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by membriux** [Albertwo512/X-B2#2]
- [x] Setup react project using `npx create-react-app .` (inside your project folder)

**Comment by Albertwo512** [comment]
i create react app, but i have to change the name project because the name can no longer contain capital letters
<img width="642" alt="Captura de pantalla 2024-05-15 a la(s) 12 56 42" src="https://github.com/Albertwo512/X-B2/assets/122117432/f28a0472-046d-431c-b636-16c971807c28">
<img width="1680" alt="Captura de pantalla 2024-05-15 a la(s) 12 57 13" src="https://github.com/Albertwo512/X-B2/assets/122117432/c46b7a84-d7e1-4692-ad38-88e055f2c20e">

**Comment by membriux** [comment]
@Albertwo512  please create a branch, push code to that branch, and finally create a Pull Request with the code changes so I can review
